[package]
name = "rust_to_xlang"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = { version = "2.0", features = ["full", "parsing", "extra-traits"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
quote = "1.0"
